import { useState } from 'react'
import type { FormEvent } from 'react'
import type { BusinessOffering, BusinessProfile } from '../types'
import { addBusinessOffering, businessProfileStore, removeBusinessOffering, updateBusinessOffering, updateBusinessProfile } from '../store/businessProfile'
import { dispatch, useAppState } from '../store/router'
import { profileRouteTools } from '../tools/businessProfile'
import { useTools } from '../webmcp'

const IDR = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const chips = (items: string[]) => <div className="profile-chips">{items.map((item) => <span key={item}>{item}</span>)}</div>
function Group({ label, items }: { label: string; items: string[] }) { return <div className="profile-group"><h3>{label}</h3>{chips(items)}</div> }

export function Products() {
  const profile = businessProfileStore.use()
  const { isBusinessProfileEditing } = useAppState()
  useTools(profileRouteTools(isBusinessProfileEditing))
  const score = Math.min(100, Math.round((8 + profile.offerings.length) / 10 * 100))
  return <section className="profile-workspace" aria-labelledby="profile-title">
    <aside className="profile-sidebar"><div className="profile-identity card"><div className="profile-avatar">{profile.name.slice(0, 1)}</div><p className="eyebrow">Business profile</p><h2>{profile.name}</h2><p>{profile.industry}</p><div className="profile-completeness"><strong>{score}% complete</strong><span><i style={{ width: `${score}%` }} /></span><small>Shared context for every agent brief.</small></div></div><div className="context-quality card"><p className="eyebrow">Context quality</p><h3>Ready for agent work</h3><p>Narrative, audience, voice, goals, guardrails, and {profile.offerings.length} structured offerings are available.</p></div></aside>
    <div className="profile-main"><header className="workspace-head"><div><p className="eyebrow">Profile</p><h1 id="profile-title">About {profile.name}</h1><p className="muted">The source of truth agents use before turning a trend into a brief.</p></div><button className="button button-primary" type="button" data-testid="edit-business-profile" onClick={() => dispatch({ type: 'setBusinessProfileEditing', editing: true })}>Edit business profile</button></header>
      <section className="card profile-about"><div className="profile-facts"><div><small>Industry</small><strong>{profile.industry}</strong></div><div><small>Offerings</small><strong>{profile.offerings.length}</strong></div><div><small>Last updated</small><strong>{new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(profile.updatedAt))}</strong></div></div><p>{profile.description}</p><Group label="Target audience" items={profile.targetAudiences}/><Group label="Brand voice" items={profile.brandVoices}/><Group label="Content goals" items={profile.contentGoals}/></section>
      <section><div className="section-heading"><div><p className="eyebrow">Sellable context</p><h2>Offerings</h2></div></div><div className="offering-grid">{profile.offerings.map((offering) => <OfferingCard offering={offering} key={offering.id}/>)}</div></section>
      <section className="claim-guardrails card"><div><p className="eyebrow">Shared claim guardrails</p><h2>Keep every brief on-brand</h2></div><Group label="Approved" items={profile.approvedClaims}/><div className="prohibited"><Group label="Prohibited" items={profile.prohibitedClaims}/></div></section>
      {isBusinessProfileEditing && <ProfileEditor profile={profile} onClose={() => dispatch({ type: 'setBusinessProfileEditing', editing: false })}/>}</div>
  </section>
}
function OfferingCard({ offering }: { offering: BusinessOffering }) { return <article className="offering-card card"><div><h3>{offering.name}</h3><strong>{IDR.format(offering.priceIdr)}</strong></div><p>{offering.positioning}</p><Group label="Unique selling points" items={offering.usp}/><div className="offering-claims"><Group label="Approved claims" items={offering.approvedClaims}/><Group label="Avoid" items={offering.prohibitedClaims}/></div></article> }

function ProfileEditor({ profile, onClose }: { profile: BusinessProfile; onClose: () => void }) {
  const [draft, setDraft] = useState(() => ({ ...profile, targetAudiences: profile.targetAudiences.join('\n'), brandVoices: profile.brandVoices.join('\n'), contentGoals: profile.contentGoals.join('\n'), approvedClaims: profile.approvedClaims.join('\n'), prohibitedClaims: profile.prohibitedClaims.join('\n') }))
  const lines = (value: string) => value.split('\n').map((item) => item.trim()).filter(Boolean)
  const save = (event: FormEvent) => { event.preventDefault(); updateBusinessProfile({ name: draft.name.trim(), description: draft.description.trim(), industry: draft.industry.trim(), targetAudiences: lines(draft.targetAudiences), brandVoices: lines(draft.brandVoices), contentGoals: lines(draft.contentGoals), approvedClaims: lines(draft.approvedClaims), prohibitedClaims: lines(draft.prohibitedClaims) }); onClose() }
  return <aside className="profile-editor card" data-testid="business-profile-editor" aria-label="Edit business profile"><div className="editor-head"><div><p className="eyebrow">Editing profile</p><h2>Business context</h2></div><button className="icon-button" type="button" onClick={onClose} aria-label="Close profile editor">×</button></div><form className="product-form" onSubmit={save}><label><span>Business name</span><input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label><span>Industry</span><input required value={draft.industry} onChange={(e) => setDraft({ ...draft, industry: e.target.value })}/></label><label><span>About the business</span><textarea required rows={4} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })}/></label><div className="editor-lists">{[['targetAudiences', 'Target audience'], ['brandVoices', 'Brand voice'], ['contentGoals', 'Content goals'], ['approvedClaims', 'Approved claims'], ['prohibitedClaims', 'Prohibited claims']].map(([field, label]) => <label key={field}><span>{label} <small>(one per line)</small></span><textarea rows={3} value={draft[field as keyof typeof draft] as string} onChange={(e) => setDraft({ ...draft, [field]: e.target.value })}/></label>)}</div><OfferingManager offerings={profile.offerings}/><div className="editor-actions"><button className="button button-primary" data-testid="save-business-profile">Save profile</button></div></form></aside>
}
function OfferingManager({ offerings }: { offerings: BusinessOffering[] }) { const [adding, setAdding] = useState(false); return <fieldset className="offering-manager"><legend>Offerings</legend>{offerings.map((offering) => <OfferingEdit key={offering.id} offering={offering}/>)}{adding ? <OfferingEdit onDone={() => setAdding(false)}/> : <button type="button" className="text-button" onClick={() => setAdding(true)}>+ Add offering</button>}</fieldset> }
function OfferingEdit({ offering, onDone }: { offering?: BusinessOffering; onDone?: () => void }) {
  const [draft, setDraft] = useState(() => ({ name: offering?.name ?? '', positioning: offering?.positioning ?? '', priceIdr: offering?.priceIdr ?? 0, usp: offering?.usp.join('\n') ?? '', approvedClaims: offering?.approvedClaims.join('\n') ?? '', prohibitedClaims: offering?.prohibitedClaims.join('\n') ?? '' }))
  const lines = (value: string) => value.split('\n').map((item) => item.trim()).filter(Boolean)
  const save = () => { if (!draft.name.trim()) return; const value = { name: draft.name.trim(), positioning: draft.positioning.trim(), priceIdr: Number(draft.priceIdr), usp: lines(draft.usp), approvedClaims: lines(draft.approvedClaims), prohibitedClaims: lines(draft.prohibitedClaims) }; if (offering) updateBusinessOffering(offering.id, value); else { addBusinessOffering(value); onDone?.() } }
  return <div className="offering-edit"><label>Name<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })}/></label><label>Positioning<textarea rows={2} value={draft.positioning} onChange={(e) => setDraft({ ...draft, positioning: e.target.value })}/></label><label>Price (IDR)<input type="number" min="0" value={draft.priceIdr} onChange={(e) => setDraft({ ...draft, priceIdr: Number(e.target.value) })}/></label><label>USPs <small>(one per line)</small><textarea rows={2} value={draft.usp} onChange={(e) => setDraft({ ...draft, usp: e.target.value })}/></label><label>Approved claims <small>(one per line)</small><textarea rows={2} value={draft.approvedClaims} onChange={(e) => setDraft({ ...draft, approvedClaims: e.target.value })}/></label><label>Prohibited claims <small>(one per line)</small><textarea rows={2} value={draft.prohibitedClaims} onChange={(e) => setDraft({ ...draft, prohibitedClaims: e.target.value })}/></label><div><button type="button" className="text-button" onClick={save}>{offering ? 'Save offering' : 'Add offering'}</button>{offering && <button type="button" className="text-button remove-offering" onClick={() => { if (window.confirm(`Remove “${offering.name}”?`)) removeBusinessOffering(offering.id) }}>Remove</button>}</div></div>
}
