/**
 * The trend detail drawer: spike chart, clip player, samples, related keywords
 * and the summary block.
 *
 * It renders inline above the table rather than as an overlay sliding in from
 * the right, for one concrete reason: `ToolSurfacePanel` is fixed to the right
 * edge, and the single most valuable shot in the demo is four tools leaving
 * that panel as this closes. A drawer that covers the panel would hide the
 * thing it exists to demonstrate.
 *
 * Two branches, and the one without a clip was built first: `fashion` and
 * `finance` trends ship with `clipIds: []` on purpose, and that is the branch
 * most likely to be left broken.
 */

import { useEffect, useRef, useState } from 'react'
import { DemoBadge, MeasuredBadge } from '../components/Badge'
import { LineChart } from '../components/LineChart'
import { PlatformIcon } from '../components/PlatformIcon'
import { clipsForIds } from '../fixtures/clips'
import { dispatch } from '../store/router'
import { selectClip, usePlayer } from '../store/player'
import { clearTrendSummary, writeTrendSummary } from '../store/trends'
import { runAnalysis } from '../tools/trends'
import type { AnalyzeResult } from '../tools/trends'
import { PLATFORM_LABEL } from '../types'
import type { Clip, SummarySource, Trend } from '../types'

const SUMMARY_MAX = 800

/** What the provenance label says, in words a judge reads once and understands. */
const SOURCE_LABEL: Record<Exclude<SummarySource, null>, string> = {
  agent: 'written by a connected agent',
  model: 'generated by the server-side model',
  cached: 'committed fallback — not generated just now',
  human: 'typed here by hand',
}

export function TrendDetail({ trend }: { trend: Trend }) {
  const clips = clipsForIds(trend.clipIds)
  const ref = useRef<HTMLElement>(null)

  // An agent calling `open_trend` should put the trend in front of the human,
  // not merely in the DOM.
  useEffect(() => {
    ref.current?.scrollIntoView({ block: 'start', behavior: 'smooth' })
  }, [trend.id])

  return (
    <section className="card drawer" data-testid="trend-detail" ref={ref}>
      <div className="drawer-head">
        <span className="drawer-mark">
          <PlatformIcon platform={trend.platform} size={20} />
        </span>
        <div className="drawer-title">
          <h2>{trend.keyword}</h2>
          <p className="muted small">
            {PLATFORM_LABEL[trend.platform]} · {trend.category} · first seen {trend.firstSeen}
          </p>
        </div>
        <button
          type="button"
          className="chip drawer-close"
          data-testid="close-trend"
          onClick={() => dispatch({ type: 'selectTrend', trendId: null })}
        >
          close ✕
        </button>
      </div>

      {/* The panels are two columns of stacked blocks rather than one long
          left column with a short right one. The old grid put the chart and
          the player in one column and a two-line summary in the other, which
          left half the drawer empty below the fold — the layout read as
          broken before anything in it was read. */}
      <div className="drawer-grid">
        <div className="drawer-col">
          <section className="panel">
            <div className="panel-head">
              <h3>14-day spike</h3>
              <DemoBadge what="This series" />
            </div>
            <LineChart points={trend.spike} height={110} label={`${trend.keyword}, 14-day spike`} />
          </section>

          {clips.length > 0 ? (
            <ClipPanel clips={clips} />
          ) : (
            <section className="panel">
              <div className="panel-head">
                <h3>Clip</h3>
              </div>
              <p className="muted small" data-testid="no-clips">
                No clips are attached to this trend. The corpus covers beauty, food, fitness
                and tech; <em>fashion</em> and <em>finance</em> ship without video on purpose,
                so this branch of the drawer is exercised before the demo rather than during
                it. The samples are all there is to read here.
              </p>
            </section>
          )}
        </div>

        <div className="drawer-col">
          {/* Keyed on the trend, so a different trend remounts the block. A
              half-typed analysis belongs to the trend it was typed under, and
              resetting that in an effect would be a second render for
              something React can do by identity. */}
          <SummaryBlock key={trend.id} trend={trend} />

          <section className="panel">
            <div className="panel-head">
              <h3>Related</h3>
            </div>
            <div className="chips">
              {trend.relatedKeywords.map((keyword) => (
                <span key={keyword} className="chip is-static">{keyword}</span>
              ))}
            </div>
          </section>

          <section className="panel">
            <div className="panel-head">
              <h3>Samples</h3>
              <DemoBadge what="Every engagement count below" />
            </div>
            <ul className="samples">
              {trend.samples.map((sample) => (
                <li key={`${sample.author}-${sample.text.slice(0, 12)}`} className="sample">
                  <span className="sample-author">{sample.author}</span>
                  <span className="sample-text">{sample.text}</span>
                  <span className="sample-engagement">
                    {new Intl.NumberFormat('en-US').format(sample.engagement)} engagements
                  </span>
                </li>
              ))}
            </ul>
          </section>
        </div>
      </div>

      <p className="drawer-note muted small">
        Closing this removes four tools from the agent surface —{' '}
        <code>get_trend_detail</code>, <code>write_trend_summary</code>,{' '}
        <code>play_clip</code> and <code>analyze_trend</code>. Watch the panel.
      </p>
    </section>
  )
}

/* ------------------------------------------------------------------------- *
 * The player. `play_clip` writes an intent into the player store; this obeys
 * it. The human's click on a chip goes through the same store, so there is one
 * path and not two.
 * ------------------------------------------------------------------------- */

function ClipPanel({ clips }: { clips: Clip[] }) {
  const player = usePlayer()
  const videoRef = useRef<HTMLVideoElement>(null)
  const clip = clips.find((c) => c.id === player.clipId) ?? clips[0]!

  useEffect(() => {
    // Token 0 is "loaded, never asked to play" — the drawer opening should not
    // start audio in front of a judge.
    if (player.playToken === 0) return
    const video = videoRef.current
    if (!video || player.clipId !== clip.id) return
    try {
      video.currentTime = player.seekS
    } catch {
      // Seeking before metadata is loaded throws in some browsers; playing
      // still works and the position lands at zero, which is not a failure.
    }
    void video.play().catch(() => {
      // Autoplay with sound can be refused. The clip is loaded and the human
      // can press play; a rejected promise is not an error worth surfacing.
    })
  }, [player.playToken, player.clipId, player.seekS, clip.id])

  return (
    <section className="panel">
      <div className="panel-head">
        <h3>Clip</h3>
        <MeasuredBadge what="Every signal under the player" />
      </div>

      <div className="clip">
        <video
          key={clip.id}
          ref={videoRef}
          className="clip-player"
          data-testid="clip-player"
          data-clip-id={clip.id}
          src={clip.src}
          poster={clip.poster}
          preload="none"
          controls
          playsInline
        >
          {clip.captionTrack && (
            <track kind="captions" srcLang="en" label="English" src={clip.captionTrack} default />
          )}
        </video>

        <div className="clip-meta">
          <h4>{clip.title}</h4>
          <p className="muted small">
            {clip.creator} · {clip.category} · {clip.license}
          </p>
          <dl className="signals" data-testid={`clip-signals-${clip.id}`}>
            <div><dt>duration</dt><dd>{clip.signals.durationS}s</dd></div>
            <div><dt>words</dt><dd>{clip.signals.words}</dd></div>
            <div><dt>words / min</dt><dd>{clip.signals.wordsPerMinute}</dd></div>
            <div><dt>hook ends</dt><dd>{clip.signals.hookEndS}s</dd></div>
            <div><dt>segments</dt><dd>{clip.signals.segments}</dd></div>
            <div><dt>transcript</dt><dd>{clip.signals.transcriptSource}</dd></div>
          </dl>
          <p className="source-note">{clip.sourceNote}</p>
        </div>
      </div>

      {clips.length > 1 && (
        <div className="clip-picker">
          {clips.map((candidate) => (
            <button
              key={candidate.id}
              type="button"
              className={`chip${candidate.id === clip.id ? ' is-current' : ''}`}
              onClick={() => selectClip(candidate.id)}
            >
              {candidate.id}
            </button>
          ))}
        </div>
      )}
    </section>
  )
}

/* ------------------------------------------------------------------------- *
 * The summary block. Four ways in — an agent, the server model, the committed
 * fallback and this textarea — and the label always says which.
 * ------------------------------------------------------------------------- */

function SummaryBlock({ trend }: { trend: Trend }) {
  const [draft, setDraft] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<AnalyzeResult | null>(null)

  const run = async () => {
    setBusy(true)
    setResult(null)
    try {
      setResult(await runAnalysis(trend, false))
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="panel summary" data-testid="trend-summary">
      <div className="panel-head">
        <h3>Why is this rising?</h3>
        {trend.aiSummarySource && (
          <span
            className={`badge badge-source badge-source-${trend.aiSummarySource}`}
            data-testid="summary-source"
            title={SOURCE_LABEL[trend.aiSummarySource]}
          >
            {trend.aiSummarySource}
          </span>
        )}
      </div>

      {trend.aiSummary ? (
        <>
          <p className="summary-text">{trend.aiSummary}</p>
          <p className="muted small" data-testid="summary-provenance">
            {trend.aiSummarySource ? SOURCE_LABEL[trend.aiSummarySource] : ''}
            {trend.aiSummarySource === 'cached' && trend.cached
              ? ` · ${trend.cached.model}, ${trend.cached.generatedAt}`
              : ''}
          </p>
          {/* Coalesced: a record persisted by an older build of the store can
              carry `aiSummary` without `suggestedAngles`, and reading `.length`
              off that took the whole route down rather than rendering a summary
              with no angles under it. */}
          {(trend.suggestedAngles ?? []).length > 0 && (
            <>
              <h4>Suggested angles</h4>
              <ul className="angles">
                {(trend.suggestedAngles ?? []).map((angle) => (
                  <li key={angle}>{angle}</li>
                ))}
              </ul>
            </>
          )}
        </>
      ) : (
        <p className="muted small" data-testid="summary-empty">
          Nothing has written an analysis yet. Ask a connected agent why this is rising —
          it can read the clip transcripts through <code>get_trend_detail</code> and call{' '}
          <code>write_trend_summary</code> — or run the analysis below, or write it
          yourself. All three land in this block and each one is labelled with where it
          came from.
        </p>
      )}

      <div className="summary-actions">
        <button
          type="button"
          className="chip"
          disabled={busy}
          data-testid="run-analysis"
          onClick={run}
        >
          {busy ? 'analysing…' : 'Run analysis'}
        </button>
        <button
          type="button"
          className="chip"
          data-testid="edit-summary"
          onClick={() => setDraft(trend.aiSummary ?? '')}
        >
          Write it yourself
        </button>
        {trend.aiSummary && (
          <button
            type="button"
            className="chip"
            data-testid="clear-summary"
            onClick={() => {
              clearTrendSummary(trend.id)
              setResult(null)
            }}
          >
            Clear
          </button>
        )}
      </div>

      {result && !result.ok && (
        <p className="summary-error" data-testid="analysis-error">
          <strong>{result.error}</strong> — {result.message} {result.hint}
        </p>
      )}
      {result && result.ok && result.source === 'cached' && (
        <p className="muted small" data-testid="analysis-note">
          {result.note}
        </p>
      )}

      {draft !== null && (
        <form
          className="summary-form"
          data-testid="summary-form"
          onSubmit={(event) => {
            event.preventDefault()
            const text = draft.trim()
            if (!text) return
            writeTrendSummary(trend.id, text.slice(0, SUMMARY_MAX), trend.suggestedAngles, 'human')
            setDraft(null)
          }}
        >
          <textarea
            value={draft}
            rows={6}
            maxLength={SUMMARY_MAX}
            data-testid="summary-input"
            placeholder="Why do you think this is rising?"
            onChange={(event) => setDraft(event.target.value)}
          />
          <div className="summary-actions">
            <button type="submit" className="chip">Save as human</button>
            <button type="button" className="chip" onClick={() => setDraft(null)}>Cancel</button>
            <span className="muted small">{draft.length} / {SUMMARY_MAX}</span>
          </div>
        </form>
      )}
    </section>
  )
}
